name: news_app
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  cupertino_icons: ^1.0.2
  webview_flutter: ^3.0.4
  flutter_spinkit: ^5.1.0
  introduction_screen: ^3.1.1
  shared_preferences: ^2.0.15
  firebase_core: ^2.3.0
  google_mobile_ads: ^2.3.0
  firebase_messaging: ^14.1.3
  flutter_local_notifications: ^12.0.4



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-SemiBold.otf


    - family: PoppinsLight
      fonts:
        - asset: fonts/Poppins-Light.otf
